export default [
    {value: 'antiochus_empire', name: 'Antiochus Empire'},
    {value: 'arghus_crypt', name: 'Arghus Crypt'},
    {value: 'bhamka_crypt', name: 'Bhamka Crypt'},
    {value: 'chicahua_hell', name: 'Chicahua Hell'},
    {value: 'cobalt_guild', name: 'Cobalt Guilt'},
    {value: 'drioce_realm', name: 'Drioce Realm'},
    {value: 'dular_tribe', name: 'Dular Tribe'},
    {value: 'elemental_universe', name: 'Elemental Universe'},
    {value: 'ellice_royaume', name: 'Ellice Royaume'},
    {value: 'elyrth_shadow', name: 'Elyrth Shadow'},
    {value: 'felose_arcane', name: 'Felose Arcane'},
    {value: 'gregvolk_chaos', name: 'Gregvolk Chaos'},
    {value: 'haahmiah_heaven', name: 'Haahmiah Heaven'},
    {value: 'harald_rike', name: 'Harald Rike'},
    {value: 'idu_clan', name: 'Idu Clan'},
    {value: 'imkan_heaven', name: 'Imkan Heaven'},
    {value: 'julakgh_kingdom', name: 'Julakgh Kingdom'},
    {value: 'krolaer_crypt', name: 'Krolaer Crypt'},
    {value: 'kusari_guild', name: 'Kusari Guild'},
    {value: 'lathagain_impire', name: 'Lathagain Impire'},
    {value: 'mary_kingdom', name: 'Mary Kingdom'},
    {value: 'molon_great_empire', name: 'Molon Great Empire'},
    {value: 'nussorlig_realm', name: 'Nussorlig Realm'},
    {value: 'outlandish_land', name: 'Outlandish Land'},
    {value: 'paladin_armada', name: 'Paladin Armada'},
    {value: 'primordial_concord', name: 'Primordial Concord'},
    {value: 'roshri_shadow', name: 'Roshri Shadow'},
    {value: 'sahl_dynasty', name: 'Sahl Dynasty'},
    {value: 'severinus_great_empire', name: 'Severinus Great Empire'},
    {value: 'titan_universe', name: 'Titan Universe'},
    {value: 'toufiq_niqaba', name: 'Toufiq Niqaba'},
    {value: 'uvniah_shadow', name: 'Uvniah Shadow'},
    {value: 'vargan_clan', name: 'Vargan Clan'},
    {value: 'wesley_gangs', name: 'Wesley Gangs'},
    {value: 'xuelong_heaven', name: 'Xuelong Heaven'},
    {value: 'yiddenda_realm', name: 'Yiddenda Realm'},
    {value: 'zhihao_tiantang', name: 'Zhihao Tiantang'}
]