export default [
    {value: 'arghus_crypt', name: 'Arghus Crypt'},
    {value: 'bhamka_crypt', name: 'Bhamka Crypt'},
    {value: 'chicahua_hell', name: 'Chicahua Hell'},
    {value: 'cobalt_guild', name: 'Cobalt Guilt'},
    {value: 'dular_tribe', name: 'Dular Tribe'},
    {value: 'elemental_universe', name: 'Elemental Universe'},
    {value: 'ellice_royaume', name: 'Ellice Royaume'},
    {value: 'elyrth_shadow', name: 'Elyrth Shadow'},
    {value: 'harald_rike', name: 'Harald Rike'},
    {value: 'idu_clan', name: 'Idu Clan'},
    {value: 'imkan_heaven', name: 'Imkan Heaven'},
    {value: 'julakgh_kingdom', name: 'Julakgh Kingdom'},
    {value: 'krolaer_crypt', name: 'Krolaer Crypt'},
    {value: 'lale_realm', name: 'Lale Realm'},
    {value: 'mary_kingdom', name: 'Mary Kingdom'},
    {value: 'nussorlig_realm', name: 'Nussorlig Realm'},
    {value: 'okan_realm', name: 'Okan Realm'},
    {value: 'primordial_concord', name: 'Primordial Concord'},
    {value: 'roshri_shadow', name: 'Roshri Shadow'},
    {value: 'sahl_dynasty', name: 'Sahl Dynasty'},
    {value: 'shadowlimbs_forest', name: 'Shadowlimbs Forest'},
    {value: 'titan_universe', name: 'Titan Universe'},
    {value: 'toufiq_niqaba', name: 'Toufiq Niqaba'},
    {value: 'vargan_clan', name: 'Vargan Clan'},
    {value: 'wesley_gangs', name: 'Wesley Gangs'},
    {value: 'yiddenda_realm', name: 'Yiddenda Realm'}
]